spring.application.name=Nexxt_MarketPlace
spring.thymeleaf.cache=false
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false

spring.datasource.url=jdbc:mysql://localhost:3307/marketplace_java
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true